[FEAT] 탭바 명칭 변경 + 공지사항 리스트/상세 view layout 구성
BorryJJong/KnockKnock-iOS pull request #101
Opened 2022-11-03 04:56 UTC by dy-yb

## What is this PR?
- 기획 변경에 따른 탭 버튼 명칭을 변경하였습니다.
- 공지사항 리스트와 상세 화면의 ui를 구성하고 autolayout을 정의하였습니다.

## Changes
- 마이페이지의 각 메뉴 성격에 따라 버튼 or 스위치로 변경되도록 바인딩 처리하였습니다.

## Test Checklist
- none.

2022-11-12 15:45 UTC, feelsodev requested changes
리뷰 사항 확인해주세요!

2022-11-12 15:45 UTC, feelsodev commented on KnockKnock-iOS/Extension-Utilities/UIKit/UINavigationController+Ext.swift
> +//    self.navigationBar.tintColor = .black
주석은 뭘까요 🤔

2022-11-12 15:45 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/My/MyCell.swift
> +  func bind(title: String, isSwitch: Bool, isVersion: Bool, versionInfo: String) {
저번에 언급한적이 있는데 이렇게 파라미터가 많다면 Cell Model 등의 개념이 도입되면 좋을 것 같네요! 
이것도 같이 이야기 해보아요

2022-11-12 15:45 UTC, feelsodev commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    let isVersion = indexPath == IndexPath(item: 1, section: 1)
이런식으로 구성해도 되긴 하지만 좀 더 좋은 방법이 없을지 고민해보면 좋을 것 같아요!
타입에 따라 AccessoryView 를 사용도 가능합니다.

2022-11-13 02:15 UTC, dy-yb commented on KnockKnock-iOS/Extension-Utilities/UIKit/UINavigationController+Ext.swift
> +//    self.navigationBar.tintColor = .black
제대로 확인하지 못했습니다 🥲 삭제처리 하도록 하겠습니다!

2022-11-13 10:13 UTC, feelsodev commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    let isVersion = indexPath == IndexPath(item: 1, section: 1)
@dy-yb 
고민을 해보는것으로!

2022-11-19 15:46 UTC, feelsodev approved these changes
별다른 특이사항 없습니다!!

2022-11-19 15:46 UTC, feelsodev commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    )
나중에 데이터는 다른 레이어로 빠지는것으로 인지하고 있으면 되겠죠?

2022-11-19 15:54 UTC, feelsodev commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    let isVersion = indexPath == IndexPath(item: 1, section: 1)
그냥 오토레이아웃으로 구성하셨군요. 
이부분 accessoryView 로 사용하면 쉽게 될텐데 일부러 사용 안하신걸까요?

2022-11-19 15:55 UTC, feelsodev approved these changes

2022-11-19 15:55 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/My/MyCell.swift
> +    }
앗 이거 그냥 오토레이앗으로 구성하셨군요 혹시 accessoryView 에 switch 넣으면 될텐데 혹시 이유가 있을까요?

2022-11-20 05:42 UTC, dy-yb commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    )
네! 근데 어디로 빠지면 적절할까요?

2022-11-20 07:58 UTC, feelsodev commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    )
데이터 레이어에 추가 되는게 좋지 않을까요?

그래서 만약 마이페이지의 섹션이 하나 추가가 된다면 뷰의 변경이 아닌

 뷰에 뿌려질 데이터의 변경만 수행하여 마이페이지의 변경이 가능하지 않을까 싶어요!

2022-11-20 09:23 UTC, dy-yb commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    )
넵 해당 이슈는 다음 작업때 수행하도록 하겠습니다!

2022-11-20 09:24 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Cells/My/MyCell.swift
> +    }
ㅎㅎ.. 거기까지 생각하지 못했읍니다.... 수정하였습니다..

2022-11-20 09:24 UTC, feelsodev commented on KnockKnock-iOS/Scenes/My/MyViewController.swift
> +    )
넵넵!

2022-11-20 09:26 UTC, feelsodev approved these changes
확인 완료입니다!

2022-11-20 09:26 UTC, merged