[FEAT] 매장 검색 결과 무한 스크롤
BorryJJong/KnockKnock-iOS pull request #105
Opened 2022-11-13 04:41 UTC by dy-yb

## What is this PR?
- 매장 주소 검색 결과 화면에 무한스크롤을 적용하여 페이징 처리를 하였습니다.
![화면 기록 2022-11-13 13 40 00 mov](https://user-images.githubusercontent.com/40792935/201506072-5ef6d817-948f-484b-9d20-d6151d390bf1.gif)

## Changes
- 1 페이지 당 15개(임시)의 결과 값을 받아옵니다.
- 페이징 처리의 느낌을 내기 위해서 바닥에 닿았을 때 0.5초의 딜레이가 발생합니다.

## Test Checklist
- none.

2022-11-19 16:09 UTC, feelsodev requested changes
리뷰 확인부탁드립나다!

2022-11-19 16:09 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/shopSearch/ShopSearchViewController.swift
> +  private var fetchMore = true
`[p2]` page, fetchMore 데이터를 view에서 가지고 말고 언터렉터에서 가지고 있을 수 있도록 하는 방향은 어떨까요?

2022-11-19 16:09 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/shopSearch/ShopSearchViewController.swift
> +  private var fetchMore = true
정확히 정리하자면 관심사 분리를 위해서 뷰는 현재 지금 내가 몇페이지인지 알고있을 필요가 없을듯 합니다 ㅎㅎ

2022-11-19 16:09 UTC, feelsodev commented
작업사항이 작아서 리뷰하기 편하네요 ㅎㅎ

2022-11-22 08:45 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/shopSearch/ShopSearchViewController.swift
> +  private var fetchMore = true
@feelsodev `fetchMore`의 경우 스크롤이 바닥에 닿은 것을 감지할때 여러번 호출되는 현상을 방지하기 위한 변수라서 view에 남아있는 것이 적절하다고 생각되어 일단 `page` 변수만 interactor로 이동하였습니다! 수정사항 확인 부탁드려요~!

2022-11-26 05:17 UTC, feelsodev approved these changes

2022-11-26 05:17 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/shopSearch/ShopSearchViewController.swift
> +  }
[p3] 우선순위는 낮게 생각해주세요!

시/도 시/군/구 를 선택한 상태를 이것도 인터렉터에서 가지고 있는게 좋지 않을까 싶은데 말이죠 

그래서 "시/도 전체" String 값을 가지고 비교하는게 아니고 nil 인지 아닌지 판단해보는게 어떨까요?

2022-11-26 10:29 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/shopSearch/ShopSearchViewController.swift
> +  }
요 부분은 조금 생각해보고 추후에 변경해보도록 하겠습니다! 작은 작업이라 간단히 해보려고 했는데 좀 시간이 필요하네요 ㅠㅠ

2022-11-26 10:30 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/shopSearch/ShopSearchViewController.swift
> +  }
네네 아마 조금의 작업사항이 있을거에요 그럼 우선 PR은 오픈시켜 놓을까요?

2022-11-26 10:31 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/shopSearch/ShopSearchViewController.swift
> +  }
넵 그게 좋을 것 같습니다~~

2022-11-29 16:05 UTC, feelsodev approved these changes
확인 완료 👍

2022-11-29 16:05 UTC, merged