[FEAT] 댓글 삭제 기능
BorryJJong/KnockKnock-iOS pull request #134
Opened 2022-12-16 08:32 UTC by dy-yb

## What is this PR?
- 댓글 삭제 api를 연결하여 댓글삭제 기능을 작성하였습니다. 

## Changes
- 관련 method를 정의하고, 댓글 삭제 버튼 이벤트를 정의하였습니다.
- api를 통해 서버 db내의 댓글을 삭제상태로 변환하고, 다시 전체 댓글을 받아와 리로드 합니다.

## Test Checklist
- none.

https://user-images.githubusercontent.com/40792935/208042533-523edf40-67c4-4987-ace8-16ae9ecb518a.mov

2022-12-17 16:08 UTC, feelsodev approved these changes
확인 완료입니다!

2022-12-18 06:52 UTC, dy-yb commented on KnockKnock-iOS/Repository/CommentRepository.swift
> +    ] as [String: Any]
수정사항 확인부탁드립니다!

2022-12-18 08:53 UTC, feelsodev requested changes

2022-12-18 08:53 UTC, feelsodev commented on KnockKnock-iOS/Repository/CommentRepository.swift
> +    )
comment 데이터를 가지고 또 init 해야하나요?.. 
바로 encode 하면 되는것 아닌지 🤔

2022-12-18 10:25 UTC, dy-yb commented on KnockKnock-iOS/Repository/CommentRepository.swift
> +    )
반영하였습니다!

2022-12-18 10:32 UTC, feelsodev approved these changes
확인 완료 👍

2022-12-18 10:32 UTC, merged