[FEAT] 애플 로그인 기능 구현
BorryJJong/KnockKnock-iOS pull request #140
Opened 2022-12-27 10:26 UTC by dy-yb

## What is this PR?
- 애플로그인을 이용하여 회원가입 및 로그인을 수행할 수 있도록 기능을 작성했습니다.

## Changes
- `AuthenticationServices` 라이브러리를 이용하여 애플 로그인을 실행합니다.
- 기존 `AccountManager`를 소셜 별로 분리하였습니다.
- 기존의 회원가입/로그인 enity 구조를 서버 명세 변경에 따라 수정하였습니다.

## Test Checklist
- none.

2023-01-03 16:52 UTC, feelsodev requested changes
리뷰 사항 확인 부탁드립니다!

추가로 
1. 프로필 이름 입력 시 포커스 아웃이 되어야만 유효성 체크를 하는데 이 부분 입력중에 하는게 어떨까 싶은데 생각을 알려주세요~
2. 마이페이지에서 프로필수정 진입 시 바텀 탭이 없어지질 않습니다. 해당 내용도 확인 부탁드려요

2023-01-03 16:52 UTC, feelsodev commented on KnockKnock-iOS/Repository/LocalDataManager.swift
> +      UserDefaults.standard.set(profileImage, forKey: "profileImage")
[p2]
1. UserDefaults 는 Service 계층을 만들어서 관리해보는게 어떨까요?

2. LocalDataManager가 하는일이 너무 광범위합니다. 토큰저장, 닉네임저장 등 만약 저장해야하는 데이터가 늘어난다면 계속해서 메소드가 추가 될 것 같네요 SRP에도 위반하는 내용이구요 🤔

2023-01-03 16:52 UTC, feelsodev commented on KnockKnock-iOS/Repository/SNS/AccountManager.swift
> +  func logIn(
```suggestion
  func signIn(
```
이렇게 네이밍을 하는것이 더 좋은 방법이겠습니다!

2023-01-03 16:52 UTC, feelsodev commented on KnockKnock-iOS/Repository/SNS/AccountManager.swift
회원탈퇴도 

signOut 이 아닌 withDraw  같은 네이밍이 더 좋을 것 같네요!

2023-01-03 16:52 UTC, feelsodev commented on KnockKnock-iOS/Repository/SNS/KakaoLoginManager.swift
> +  func loginWithKakao(completionHandler: @escaping (String) -> Void) {
```suggestion
  func excute(completionHandler: @escaping (String) -> Void) {
```
이렇게 네이밍을 하는것이 좋겠습니다. 
`카카오 로그인 매니저` 클래스에서 `실행`을 한다로 의미하도록 말이죠
당연히 카카오 로그인 매니저니까 실행을하면 로그인을 하겠죠 
이렇게 하나의 기능만 정의가 되어있는 편이 좋겠습니다. SRP 를 잘 생각해주세요!

2023-01-03 16:52 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Login/LoginInteractor.swift
> +  /// 회원 o -> 토큰 저장 후 홈 화면 진입 / 회원 x -> 프로필 설정화면(회원가입)
```suggestion
  /// 회원 판별
  ///
  /// - Parameters:
  ///   - isExisted: 기존회원 여부
  ///   - loginInfo: 로그인 요청 정보
```

이렇게 작성하면 method summary에 나오게 됩니다 😁  xcode 에서 확인해보셔요

2023-01-03 16:52 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Login/LoginInteractor.swift
> +  func isExistUser(response: AccountResponse, loginInfo: LoginInfo) {
```suggestion
  func checkExistUser(response: AccountResponse, loginInfo: LoginInfo) {
```
요런 네이밍이 좋지 않을까요? boolean 값을 리턴하는 함수 또는 프로퍼티가 아니니까요 ㅎ

2023-01-03 16:52 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Login/ProfileSetting/ProfileSettingInteractor.swift
> +    )
사실 그냥 response 만 매개변수로 던져버리면 될텐데 말이죠

2023-01-04 05:05 UTC, dy-yb commented on KnockKnock-iOS/Repository/LocalDataManager.swift
> +      UserDefaults.standard.set(profileImage, forKey: "profileImage")
1. Userdefaults로 키를 관리하는 것이 확정되지 않았다고 생각해서 따로 service처리는 하지 않고 있었는데 그냥 계속 작업하는 것이 좋을까요?

2. 1에서 말씀해주신 것처럼 하고 있지 않다보니 나타나는 문제인 것 같기는 한데,, 만약 그거랑 상관이 없다고 한다면 Userdefaults에 회원정보를 저장/삭제/불러오기 작업을 하는 것이 광범위한지 느끼지 못했는데,, 어떻게 분리하는 것이 이상적이라고 보시는지 좀 더 디테일하게 설명해주실 수 있을까요?

2023-01-04 05:07 UTC, dy-yb commented
닉네임 유효성 검사 부분은 별도 이슈를 생성해서 작업하도록 하겠습니다!

2023-01-04 05:12 UTC, dy-yb commented
@feelsodev 네이밍은 다음과 같이 수정하였습니다.
로그인: sign in
로그아웃: sign out
회원가입: register
회원탈퇴: withdraw
api 관련 메소드는 path를 따라서 사용하고, 클래스명(e.g., LoginView, LoginInteractor)은 login이 명사로서 포괄적인 의미를 가지고 있는것 같아 아직 남겨두었는데 그것도 변경되는 것이 좋을까요?

2023-01-04 11:54 UTC, feelsodev commented
@dy-yb 님 이슈 코멘트 resolve 저희 안하는것으로 하면 어떨까요?

2023-01-04 12:03 UTC, dy-yb commented
@feelsodev 앗 제가 작업하면서 헷갈려서 resolve 처리 하고있었는데,, 그럼 전체 완료되면 풀어도 될까요..?🥹

2023-01-04 12:06 UTC, dy-yb commented
아하 넵 그렇게 해보겠습니다!🙆🏻‍♀️

2023-01-05 06:05 UTC, dy-yb commented on KnockKnock-iOS/Repository/LocalDataManager.swift
> +      UserDefaults.standard.set(profileImage, forKey: "profileImage")
@feelsodev 나름대로 반영해보았습니다,,, 확인 부탁드립니다!

2023-01-07 04:04 UTC, dy-yb commented on KnockKnock-iOS/Network/KKRequestInterceptor.swift
> +    let userDefaultsService = UserDefaultsService()
반영완료

2023-01-07 04:05 UTC, dy-yb commented on KnockKnock-iOS/Service/UserDefaultsService.swift
> +}
반영완료

2023-01-07 08:34 UTC, feelsodev approved these changes
LocalManager의 역할이 명확하지 않은 부분에 대해서는 밋업 시간이 논의하겠습니다! 

작업하느라 고생하셨습니다 🙏

2023-01-07 08:34 UTC, merged