[FEAT] feed list view layout 구성
BorryJJong/KnockKnock-iOS pull request #22
Opened 2022-06-25 13:33 UTC by dy-yb

## What is this PR?
- 피드가 리스트 형식으로 보여지는 화면을 구성하였습니다.
- 이전에 작업한 피드 뷰의 셀을 클릭하면 화면이 전환되도록 합니다.

## Changes
- FeedRouter를 이용하여 Feed View에서 Feed List View로 넘어가도록 작성하였습니다.
  - API 호출에 대한 논의가 필요해 간단한 화면 전환만 구현해두었습니다.
- ScrollView와 PageControl을 통해 게시 된 이미지가 슬라이드 됩니다.
- 게시 글의 내용이 두 줄까지 표시되고 '... 더보기'로 표시 됩니다.
  - 상세 보기로 전환이 될지, 게시글의 전체 내용이 보여질지 확인 후 버튼 액션 작업 진행할 예정입니다.

## Test Checklist
- Feed View의 셀을 클릭했을 때 두 번째 클릭에만 반응하는 이슈가 있습니다.
- 이미지가 정방형이 아닐 경우 표현되는 방식에 대한 논의가 필요해 보입니다.

2022-06-30 07:23 UTC, dy-yb commented
현재 검색 필터(tag)의 맨 첫 번째 셀이 선택 된 상태로 나타나지 않는 이슈가 있습니다. 리뷰하실 때 해당 부분 살펴봐주시면 좋을 것 같습니다!

2022-07-02 13:29 UTC, feelsodev requested changes
늦게 리뷰를 남겨드려 죄송합니다. 코멘트 남겨놓은 부분 확인 부탁드릴게요!

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Entity/Challenge.swift
> +struct ChallengeTitle: Codable {
```suggestion
struct ChallengeTitle: Decodable {
```
저희는 Decode 용으로 Entity를 사용하고 있으니 Decodable 이 더 명확해 보입니다! 다른것도 변경 부탁드려요

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Extension-Utilities/UIKit/UILabel+Ext.swift
> +  var visibleTextLength: Int {
```suggestion
  /// Summary
  var visibleTextLength: Int {
```
`///`   주석으로 Summary 를 적어주시면 더 무슨일을 하는지 알기 쉬워 보입니다! 

그렇게 되면 해당 함수나 프로퍼티에 option + 클릭을 하게되면 Summary가 나오기 때문에 좋습니다. 
구두로 나중에 또 알려드릴게요

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Network/KKRouter.swift
> +  case fetchFeed
네트워크 타입의 네이밍에 대해서도 따로 이야기 나누어 보시죠~

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedCell.swift
> +    }
```suggestion
    if feed.images.count > 1 {
      self.severalSymbolImageView.isHidden = false
    } else {
      self.severalSymbolImageView.isHidden = true
    }
```
이것도 사실 재사용시에 문제가 될 수 있어요 
이미지 갯수가 1 이상이라면 다음과 같이 `self.severalSymbolImageView.isHidden = false` 처리를 해주고 있는데 저 조건에 해당되지 않는 경우의 cell 에서도 isHidden이 false 나타나는 케이스가 발생가능합니다.

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedCell.swift
> +    }
+ 추가로 더 간단한게 표현한다면 
```suggestion
    self.severalSymbolImageView.isHidden = feed.images.count <= 1 
```

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedListCell.swift
> +class FeedListCell: BaseCollectionViewCell {
```suggestion
final class FeedListCell: BaseCollectionViewCell {
```
final 을 작성하는게 처음에는 익숙하지 않죠 ㅎㅎ 확인 부탁드립니다.

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedListCell.swift
> +  ).then {
```suggestion
  private lazy var stackView = UIStackView(arrangedSubviews: [
    self.userIdLabel,
    self.postDateLabel
  ]).then {
```
개행 방법이 이게 적절해 보이는군요

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedListCell.swift
> +                                 height: width * 1.333)
```suggestion
        imageView.frame = CGRect(
          x: xPosition,
          y: 0,
          width: width,
          height: width * 1.333
        )
```
저희 컨벤션에 의하면 개행은 이런 방식으로 👍

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedListCell.swift
> +  func setImageView(images: [String], scale: String) {
```suggestion
  private func setImageView(images: [String], scale: String) {
```
이것도 `FeedListCell` 안에서만 사용되는 메소드이므로 private 키워드를 넣어주세요! 그러면더 코드리뷰, 코드수정 등 코드를 다시 보게되는 경우에 더 명확해집니다. (아 이거는 해당 클래스 안에서만 쓰여지는 클래스이구나!! 라고 말이죠)

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedListCell.swift
> +      case "3:4":
이런 "3:4" 의 String 매칭 보다는 enum으로 관리하는게 더 좋아보여요

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +    cell.backgroundColor = .white
셀의 배경색상은 여기서 할 필요 없어보이는군요?

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +        height: ((self.containerView.frame.width - 40) + 170))
이것도 마찬가지로 enum 타입을 사용하면 더 좋겠어요.

2022-07-02 13:29 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/FeedListCell.swift
> +
cell을 바인딩 할 때 조건이 명확하다면 이것도 사실 필요없어집니다.

2022-07-03 14:43 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +    cell.backgroundColor = .white
배경색상을 설정하는 올바른 위치가 어디일까요? 저도 계속 저 부분에 두고싶지 않아서 고민해보았는데 다른 적당한 곳을 찾지 못하였습니다..

2022-07-03 14:44 UTC, bejewel-sangwon commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +    cell.backgroundColor = .white
FeedListCell 클래스 내부에 하면 되지 않을까요?? 🤔

2022-07-03 14:45 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +    cell.backgroundColor = .white
FeedListCell 내부에 하면 되지 않을까요?

2022-07-03 14:52 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +    cell.backgroundColor = .white
아아.. layoutSubviews() 메소드 이용하면 되겠군요..! 혹시 부적절한 메소드라고 생각하시면 말씀해주세요~

2022-07-03 14:56 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +    cell.backgroundColor = .white
layoutSubviews가 언제 불리우는지 라이프 사이클을 먼저 찾아보고 판단하는게 좋을듯 싶네요.
그리고 이미 BaseCollectionViewCell 에 `func setupConstraints()`를 사용하는 것처럼 사용하시면 될텐데 약간 다른 부분에서 이해가 안되신 느낌이군요??..

2022-07-04 03:33 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedList/FeedListViewController.swift
> +    cell.backgroundColor = .white
`BasecCollectionView` `init` 부분에서 `backgroundColor`가 `.black`으로 되어있는 것을 지금 확인했네요. 해당 부분 변경하여 적용했습니다. 라이프사이클에 대해서는 좀 더 알아보도록 하겠습니다.

2022-07-04 15:13 UTC, dy-yb commented
![스크린샷 2022-07-05 00 12 22](https://user-images.githubusercontent.com/40792935/177181717-f669fc9b-fdb4-4eaa-845b-229df81d15ac.png)
해당 화면에서 첫 번째 셀이 디폴트로 선택되지 않는 문제가 있다고 코멘트 남겼었는데 리뷰 누락 된 것 같아서 재차 말씀드립니다!

2022-07-05 12:37 UTC, feelsodev commented
@dy-yb 
태그 관련 문제는 구두로 논의하여 완료 처리하겠습니다!

2022-07-05 12:37 UTC, feelsodev approved these changes
확인 완료입니다.

2022-07-05 12:37 UTC, merged