[FEAT] tag cell selected event logic 변경
BorryJJong/KnockKnock-iOS pull request #26
Opened 2022-07-06 05:31 UTC by dy-yb

## What is this PR?
- 피드 검색에 사용 될 tag의 선택/비선택 상태 변화 이벤트 로직을 수정하였습니다.

## Changes
- `ChallengeTitle` entity에 `isSelected` property를 추가하여 선택 상태를 관리합니다.
- 초기 화면은 '전체'가 선택 된 상태로 나타납니다.
- 다른 tag 선택시 기존에 선택 한 tag는 선택이 해제 됩니다.

## Test Checklist
- 현재 사용 중인 'Tag' 명칭에 대한 논의가 필요해보입니다.

2022-07-06 15:59 UTC, feelsodev requested changes
리뷰사항 확인해주세요!

2022-07-06 15:59 UTC, feelsodev commented on KnockKnock-iOS/Entity/Challenge.swift
> +  }
struct 모델(Entity)는 크게 3가지가 될 수 있습니다.
`[1]` Decode를 하기위한 Entity -> API Response 데이터를 담기 위한 모델링
`[2]` Encode를 하기위한 Entity -> API Request 데이터를 담기 위한 모델링
`[3]` UI(View)를 위한 Entity(ViewModel) -> 뷰를 핸들링 하기 위한 모델링

현재 `struct ChallengeTitle: Decodable { ... }` 기준으로
id, title 값은 서버에서 받아오는 경우로 `[1]`에 해당됩니다.
isSelected 값은 `[3]` 에 해당 됩니다. 이 부분을 나누어 사용할지 아니면 통합해서 사용할지에 대해 추후 논의해보면 좋겠습니다~

2022-07-06 15:59 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/TagCell.swift
> +  func setLabel(isSelected: Bool) {
```suggestion
  private func setLabel(isSelected: Bool) {
```
접근지정자 명시 필요

2022-07-06 15:59 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +        }
셀을 선택하는 비즈니스 로직을 구현하셨군요.
다만 이 로직이 다른 영역에 있는게 좋지 않을까 싶습니다. 예를들면 Interactor, worker 등에서 말이죠
단순히 뷰에서는 클릭된 Index 값을 interactor 에게 전달 하고 그 비즈니스 로직을 거친 [ChallengeTitle] 데이터를 다시 뷰에서 갱신받아 반영시키기만 하는 구조가 더 좋은구조로 생각됩니다. 

정리하자면 뷰에서는 어떤 것을 눌렀는지만 비즈니스 로직에 전달하고 뷰는 현재 가지고 있는 데이터에 대한 변형(mutate)를 할 필요가 없습니다.
그렇게 되면 예시로  `interactor?.didSelectdTag(index: index)` 한줄로 뷰에서의 역할은 끝나지 않을까 싶네요

2022-07-09 03:12 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Cells/TagCell.swift
> +  func setLabel(isSelected: Bool) {
해당 메소드는 현재 ViewController에서 셀 선택시 다시 호출되기 때문에 private 처리 하지 않았습니다.

2022-07-10 05:18 UTC, dy-yb commented
@feelsodev 리뷰해주신 내용 반영처리 했으니 확인 부탁드립니다! 그런데 제가 지난 번에 성민님께 확인한 바로는 tag section이 아래로 스크롤 되었을 때 고정되어 있어야 한다고 하시는데, 그 경우에는 다시 이전처럼 collectionView가 분리 된 형태로 변경해야 할까요?🤔

2022-07-10 09:56 UTC, bejewel-sangwon commented
@dy-yb stickyHeader 라는 키워드로 검색하시면 이와 관련된 자료가 나올거에요. 
다만 저희는 무조건 상단에 고정이니 그냥 컬렉션뷰가 더 나을수도 있겠다는 생각이 들기도 하네요. 
다예님 원하시는 방향으로 해보시죠~

2022-07-10 09:57 UTC, feelsodev commented
@dy-yb stickyHeader 라는 키워드로 검색하시면 이와 관련된 자료가 나올거에요.
다만 저희는 무조건 상단에 고정이니 그냥 컬렉션뷰가 더 나을수도 있겠다는 생각이 들기도 하네요.
다예님 원하시는 방향으로 해보시죠~

2022-07-10 11:26 UTC, feelsodev requested changes
FeedViewController 57번 라인 `// MARK: - Extensions` 주석 네이밍을 변경하는게 어떨까요?? 너무 포괄적인 의미라서요.
결국 크게 보았을때 `self.interactor?.fetchFeed()`, `self.interactor?.getChallengeTitles()`는 input action으로 보여지고 FeedViewProtocol 에 의한 이벤트 호출을 output action으로 보여지니 적절히 고민해보면 좋겠습니다!

리뷰사항 확인해주세요!

2022-07-10 11:26 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +      )
뷰에서 FeedListRouter.createFeedList() 호출할 필요가 없어보여요.
라우터에서 할 수 있도록 변경하는게 좋겠습니다.

2022-07-10 11:29 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +          animated: false)
어떤 애니메이션을 말씀하시는 걸까요?? reload 하면서 섹션 전체가 깜빡거리는 현상이 있어서 일단 애니메이션을 해제해두었습니다.

2022-07-10 11:30 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +          animated: false)
지금 `.centeredHorizontally` 옵션이 들어가서 스크롤시에 딱딱 바로 이동이 적용되는데 부자연스러워서요

2022-07-10 11:40 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +          animated: false)
animated를 true로 먹여도 좀 이상하군요 🤔

2022-07-10 11:41 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +          animated: false)
아하~ 리로드하면서 클릭했던 위치로 갈 수 있으면 가장 좋을 것 같은데 딱 알맞은 방법을 찾지 못했습니다...😅

2022-07-10 11:42 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +          animated: false)
애니메이션이 생기면 0번째부터 해당 위치까지 움직이기 때문에 제가 보기에는 좀 더 부자연스러워지는 것 같습니다..

2022-07-10 11:44 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedInteractor.swift
>    func getChallengeTitles()
지난 번 미팅 때 말씀드렸다시피 네이밍은 전부 api에 맞추어 붙이고 있고, feed 조회의 경우 api가 아직 나오지 않아서 네이밍은 추후 api가 나오는데로 변경 될 것 같습니다.

2022-07-10 11:48 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedViewController.swift
> +          animated: false)
이건 해결 방법을 좀 찾아봐야 할 것 같군요

2022-07-10 11:48 UTC, dy-yb commented
@feelsodev 해당 내용은 tagCollectionView, feedCollectionView 총 두 개의 CollectionView로 구성해보겠습니다.

> @dy-yb stickyHeader 라는 키워드로 검색하시면 이와 관련된 자료가 나올거에요.
> 다만 저희는 무조건 상단에 고정이니 그냥 컬렉션뷰가 더 나을수도 있겠다는 생각이 들기도 하네요.
> 다예님 원하시는 방향으로 해보시죠~

2022-07-10 11:50 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedInteractor.swift
>    func getChallengeTitles()
네네 fetch 때문에 왜 다르게 했을까 질문드렸습니다. 추후 변경하는것으로 알고 있겠습니다~

2022-07-10 11:51 UTC, feelsodev commented
@dy-yb  넵넵 알겠습니다 💪

2022-07-12 11:40 UTC, dy-yb commented
@feelsodev 셀 선택 애니메이션 이외에 리뷰 사항 모두 반영 되었으니 확인 부탁 드립니다~

2022-07-16 05:08 UTC, feelsodev approved these changes
확인 완료입니다!

2022-07-16 05:18 UTC, merged