[FIX] Bottom modal 이상 동작 이슈 해결
BorryJJong/KnockKnock-iOS pull request #30
Opened 2022-07-13 05:12 UTC by dy-yb

## What is this PR?
- `BottomSheetView.topAnchor` 값을 결정하는 스크린의 전체 높이가 0으로 반환되면서 동작 시 위에서 아래로 떨어지는 현상을 해결하였습니다.

## Changes
- `UIDevice extension`에 `heightOfSafeArea()` 메소드를 추가하였습니다.
  - 현재 보여지고 있는 화면의 height에서 safeAreaInset(위, 아래)를 뺀 값을 반환합니다.

## Test Checklist
- none.

2022-07-16 05:05 UTC, feelsodev approved these changes
동작 확인했습니다!

2022-07-16 05:05 UTC, feelsodev commented on KnockKnock-iOS/Extension-Utilities/UIKit/UIDevice+Ext.swift
> +    guard let rootView = UIApplication.shared.keyWindow else { return 0 }
여기서 deprecated warning 뜨는데 수정 부탁드려요~~

2022-07-16 07:14 UTC, dy-yb commented on KnockKnock-iOS/Extension-Utilities/UIKit/UIDevice+Ext.swift
> +    guard let rootView = UIApplication.shared.keyWindow else { return 0 }
수정했으니 확인부탁드립니다~

2022-07-21 15:57 UTC, feelsodev requested changes

2022-07-21 15:57 UTC, feelsodev commented on KnockKnock-iOS/Extension-Utilities/UIKit/UIDevice+Ext.swift
>      if #available(iOS 11.0, *) {
버전 분기처리 구문은 필요없지 않을까요?? 
저희 지금 프로젝트가 최소버전 15이상이니

2022-07-21 23:39 UTC, dy-yb commented on KnockKnock-iOS/Extension-Utilities/UIKit/UIDevice+Ext.swift
>      if #available(iOS 11.0, *) {
앗 최소 버전 13으로 하시려고 했던거 아니었나요??

2022-07-21 23:57 UTC, feelsodev commented on KnockKnock-iOS/Extension-Utilities/UIKit/UIDevice+Ext.swift
>      if #available(iOS 11.0, *) {
앗 그랬던가여 기억이,,,ㅎ 프로젝트에 타겟버전 13으로 조정 부탁드려요! 
어차피 최소버전 13으로 해도 저 구문은 필요없지 않을까요??

2022-07-22 03:27 UTC, dy-yb commented on KnockKnock-iOS/Extension-Utilities/UIKit/UIDevice+Ext.swift
>      if #available(iOS 11.0, *) {
ㅎㅎ 넵 코드는 수정하겠습니다~~

2022-07-22 15:49 UTC, feelsodev approved these changes
확인 완료입니다. 머지할게요!

2022-07-22 15:49 UTC, merged