[FEAT] 댓글 입력 창 ui 구성
BorryJJong/KnockKnock-iOS pull request #32
Opened 2022-07-16 07:50 UTC by dy-yb

## What is this PR?
- 댓글을 입력할 입력창 부분의 ui를 구성하였습니다.

## Changes
- TextView를 이용하여 댓글 입력창을 만들고, 3줄까지 댓글 창이 늘어나다가 4줄 이상 부터는 스크롤이 활성화 됩니다.
- 키보드가 올라가면 댓글창이 함께 올라가게되고, 디자인에 따라서 기존에 설정된 마진 값도 변경됩니다.
- 키보드가 활성화 되었을 때 키보드 이외의 화면을 터치하면 키보드가 비활성화 되는 메소드를 추가하였습니다.(UIViewController extension)

## Test Checklist
- 댓글의 라인이 증가하면서 댓글창이 늘어날 때 약간 부자연스러운 느낌이 있습니다..

2022-07-21 16:03 UTC, feelsodev requested changes
<img width="429" alt="스크린샷 2022-07-22 오전 1 01 52" src="https://user-images.githubusercontent.com/59601439/180260653-940fb09d-1f29-4903-b101-d8a79245211a.png">
코드 보기전에 일단 빌드 테스트 먼저 해봤는데 사진처럼 레이아웃이 뭉게지는군요 ㅠㅠ 확인 부탁드립니다!!

2022-07-22 01:58 UTC, dy-yb commented
해당 이슈 해결 되었습니다~ 확인부탁 드려요!

2022-07-24 12:37 UTC, feelsodev commented
키보드가 올라왔을때 텍스트를 작성하면 키보드가 내려가는군요 ㅠㅠ 이 부분 확인 부탁드려요!

2022-07-24 12:39 UTC, dy-yb commented
아마 해당 이슈는 앱내 키보드로 입력하지 않으셔서 그런 것 같은데 이 것도 문제가 될까요?? 올라온 키보드를 클릭해서 입력하면 해당 문제는 발생하지 않습니다.. + 혹시나해서 제가 기기에서 빌드 테스트 했을 때는 잘 작동하는 것으로 확인했습니다!

2022-07-24 12:45 UTC, feelsodev commented
아?? 이런 경우가 있군요 몰랐네요 이 방법으로 다음부턴 테스트하면 안되겠네요 😭 
추가로 드래그 했을때 자동완성 기능을 끄는게 어떨까요?? 빨갛게 되는 부분입니다!! 의도치 않게 유저의 텍스트가 변경 될 수 있어서요.
+ 머지 컨플릭만 해결 부탁드립니다! 

![스크린샷 2022-07-24 오후 9 42 51](https://user-images.githubusercontent.com/59601439/180647585-07a159b6-589e-4423-a9c7-f1f1fce76133.png)

2022-07-24 12:49 UTC, feelsodev approved these changes

2022-07-24 12:49 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/ReplyCell.swift
> +class ReplyCell: BaseCollectionViewCell {
```suggestion
final class ReplyCell: BaseCollectionViewCell {
```

2022-07-24 12:50 UTC, feelsodev approved these changes

2022-07-24 12:50 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/Comment/Views/CommentView.swift
> +    $0.autocorrectionType = .no
$0.spellCheckingType = .no  이 옵션도 필요해요!

2022-07-24 12:55 UTC, feelsodev commented
고생하셨습니다!! 머지할게요

2022-07-24 12:55 UTC, merged