[FEAT] pager animation 수정(이동 -> 길이변경)
BorryJJong/KnockKnock-iOS pull request #62
Opened 2022-09-04 04:36 UTC by dy-yb

## What is this PR?
- 홈 화면의 메인 부분 `pager`의 애니메이션 작동 방식을 변경하였습니다.
![화면 기록 2022-09-04 13 35 25 mov](https://user-images.githubusercontent.com/40792935/188297608-5c5446f0-67f2-48b1-992d-a04d9701a6a2.gif)

## Changes
- `pager`의 기능을 하는 `lineView`의 길이를 변경하는 방식을 사용하였습니다.

## Test Checklist
- none.

2022-09-11 18:13 UTC, feelsodev reviewed
리뷰사항 확인해주세요!

2022-09-11 18:13 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/Home/HomeMainPagerCell.swift
> +    self.lineView.widthConstraint?.constant = (lineViewLength * currentPage) + lineViewLength
저희는 오토레이아웃을 사용하니까 frame 조정말고 constraints 로 해보면 어떨까요??

snapKit 에서는 updateConstraints도 지원하니 이것도 찾아보며 좋을 것 같아요!

2022-09-13 07:58 UTC, dy-yb commented
@feelsodev 피드백 반영하였습니다~!

2022-09-14 15:55 UTC, feelsodev requested changes
리뷰 사항 화인해주세요!

2022-09-15 02:50 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Cells/Home/HomeMainPagerCell.swift
> +    }
완전 심플하게 구현 할 수 있었네요,,ㅎㅎ 반영하였습니다!

2022-09-15 15:59 UTC, feelsodev approved these changes
내용 확인했습니다! 머지 할게요

2022-09-15 15:59 UTC, merged