[FEAT] 설정 화면 layout
BorryJJong/KnockKnock-iOS pull request #86
Opened 2022-10-08 14:14 UTC by dy-yb

## What is this PR?
- 설정 화면의 기본적인 layout을 구성하였습니다.

## Changes
- 리스트 형태의 collectionView를 구성하였습니다.

## Test Checklist
- None.

2022-10-09 05:11 UTC, feelsodev requested changes
다예님 리뷰 사항 확인해서 수정해주세요!

2022-10-09 05:11 UTC, feelsodev commented on KKDSKit/Sources/KKDSKit/KKDS+UIKit/KKDSButton.swift
> +  }
[p1]
확장성이나 관리 측면에서 프로퍼티 형식이 아닌 UIButton 을 상속받는 형태의 클래스 형태로 아예 하나 빼서 구성하는게 좋을 것 같아요!
예시로는
```
public final class MiddleButton: UIButton {

    init() { ... }
    // do something
}
```

2022-10-10 04:12 UTC, dy-yb commented on KKDSKit/Sources/KKDSKit/KKDS+UIKit/KKDSButton.swift
> +  }
해당 사항 수정 처리했으니 확인부탁드립니다👍🏼

2022-10-10 12:07 UTC, feelsodev requested changes

2022-10-10 12:07 UTC, feelsodev commented on KKDSKit/Sources/KKDSKit/KKDS+UIKit/KKDSButton.swift
> +      ),
컬러도 성민님이 작업해주신 컬러 에셋들도 KKDSKit 에 추가해서 사용해도 좋을 것 같아요! 엄청 오래 걸리는건 아니니까 이것만 추가해주시겠어요?

2022-10-11 03:19 UTC, dy-yb commented on KKDSKit/Sources/KKDSKit/KKDS+UIKit/KKDSButton.swift
> +      ),
다른 부분에서 기존의 color asset 사용하고 있는 부분은 추후에 바꿔 나가도록 하겠습니다~~

2022-10-11 15:20 UTC, feelsodev approved these changes
내용 확인했습니다 👍

2022-10-11 15:20 UTC, merged