[FEAT] 피드 작성 데이터 전달
BorryJJong/KnockKnock-iOS pull request #92
Opened 2022-10-22 15:10 UTC by dy-yb

## What is this PR?
- 피드 등록 시 사용자가 입력한 태그/챌린지/주소의 값이 피드 작성 화면으로 전달되도록 하였습니다.

## Changes
- delegate 패턴을 이용하여 property/address view(child) -> feedWrite(parent)로 데이터가 전달됩니다.

## Test Checklist
- none.

2022-10-23 15:54 UTC, feelsodev requested changes
FeedWriteViewController 로 직접 데이터를 전달하게 되는데 interactor로 전달하여 데이터 처리를 하는게 좋겠어요! 구두로 이야기 해봐요 이건~

2022-10-23 15:54 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Cells/PropertyCell.swift
> +//      self.checkButton.trailingAnchor.constraint(equalTo: self.contentView.safeAreaLayoutGuide.trailingAnchor)
```suggestion
```
삭제 필요!

2022-10-24 00:33 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Cells/PropertyCell.swift
> +//      self.checkButton.trailingAnchor.constraint(equalTo: self.contentView.safeAreaLayoutGuide.trailingAnchor)
삭제처리했습니다!

2022-11-11 15:33 UTC, feelsodev approved these changes
리뷰 사항 확인해주세요!

2022-11-11 15:33 UTC, feelsodev commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/PropertySelectViewController.swift
> +    }
PropertySelectViewController 는 태그랑 키워드 데이터가 왜 ViewController에 존재할까요? 
혹시 추가 예정일까요 🤔  추가 예정이라면 이번엔 머지하도록 하겠습니다!

2022-11-12 00:05 UTC, dy-yb commented on KnockKnock-iOS/Scenes/Feed/FeedWrite/PropertySelectViewController.swift
> +    }
네 다른 브랜치에서 해당 부분 수정되었습니다! 다음 작업사항 리뷰 때 확인해주시면 될 것 같습니다😀

2022-11-12 00:48 UTC, merged